version: '3.3'

services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres-assertiva
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assertiva
    ports:
      - "5433:5432"
    networks:
      - database
  assertiva:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CACHE_PATH: /tmp/build_cache
    tty: true
    ports:
      - "8080:8080"
    networks:
      - database
    depends_on:
      - db
  debugger:
    image: azul/zulu-openjdk:17
    container_name: assertiva-debugger
    ports:
      - "5005:5005"
    networks:
      - database
    depends_on:
      - assertiva
networks:
  database:
    driver: bridge